apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: processflowpro-ingress
  namespace: processflowpro
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - app.processflowpro.de
      secretName: processflowpro-tls
  rules:
    - host: app.processflowpro.de
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80
